services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./.env.docker:/app/.env.docker
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.docker
    command: >
      poetry run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    depends_on:
      - db

  app-debug:
    build:
      context: .
    volumes:
      - ./app:/app/app
      - ./.env.docker:/app/.env.docker
    ports:
      - "8001:8000"
      - "5678:5678"
    env_file:
      - .env
      - .env.docker
    depends_on:
      - db
    command: >
      poetry run python -m debugpy
      --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
