name: Coveralls

on:
  pull_request:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: story_narrator_test
          POSTGRES_USER: story_user
          POSTGRES_PASSWORD: story_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U story_user -d story_narrator_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U story_user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run tests with coverage
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: story_narrator_test
          DB_USER: story_user
          DB_PASSWORD: story_password
        run: |
          poetry run pytest --cov=. --cov-fail-under=70

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run coveralls
